# Generated by Django 5.0.2 on 2024-02-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.DecimalField(decimal_places=1, max_digits=1000),
        ),
    ]
